config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { :omniauth_callbacks => 'callbacks' }

  root to: 'checklists#index'
  get '/checklists/accept' => 'checklist_shares#accept', as: :accept_checklist
  resources :checklists do
    resources :checklist_items
  end
  resources :checklist_shares, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/checklist.rb
class Checklist < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  has_many :checklist_items, dependent: :destroy

  def all_done?
    checklist_items.pluck(:completed).all?
  end

  def share_with(current_user, email)
    user = User.find_by(email: email)
    user ||= User.create_with_password(email: email)
    ChecklistShare.find_or_create_by(user: user, checklist: self)
    MailerJob.perform_async("ShareChecklistMailer", :email, current_user.id, user.id,self.id)
  end
end

app/models/checklist_item.rb
class ChecklistItem < ApplicationRecord
  belongs_to :checklist
  validates :title, presence: true

  has_attached_file :image
  validates_attachment_content_type :image, content_type: %r{/\Aimage\/.*\z/}
end

app/models/checklist_share.rb
class ChecklistShare < ApplicationRecord
  belongs_to :user
  belongs_to :checklist
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable,
    :omniauthable, omniauth_providers: [:github]

  has_many :checklists, dependent: :destroy

  def self.create_with_password(email: new_email)
    user = User.new(email: email)
    user.password = Devise.friendly_token[0, 20]
    user.save!
    user
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      # user.name = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def authenticate_admin!
    redirect_to new_user_session_path unless current_user&.admin?
  end

  def authenticate_user!
    redirect_to new_user_session_path unless current_user
  end
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: 'Github') if is_navigational_format?
    else
      session['devise.github_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/checklist_items_controller.rb
class ChecklistItemsController < ApplicationController
  before_action :find_checklist, only: %i[new create edit destroy]

  def new
    @checklist_item = ChecklistItem.new(checklist: @checklist)
  end

  def create
    @checklist_item = ChecklistItem.new(checklist_item_params)
    @checklist_item.checklist = @checklist
    @checklist_item.save!
    flash[:success] = 'Item created'
    redirect_to @checklist
  end

  def edit
    @checklist_item = @checklist.checklist_items.find(params[:id])
  end

  def destroy
    @checklist_item = @checklist.checklist_items.find(params[:id])
    @checklist_item.destroy
    redirect_to @checklist
  end

  def update
    @checklist_item = ChecklistItem.find(params[:id])
    if @checklist_item.update(checklist_item_params)
      flash[:success] = 'Item updated!'
    else
      flash[:error] = 'Failed to update the item.'
    end
    redirect_to @checklist_item.checklist
  end

  private

  def find_checklist
    @checklist = Checklist.find(params[:checklist_id])
  end

  def checklist_item_params
    params.require(:checklist_item).permit(:title, :completed)
  end
end

app/controllers/checklist_shares_controller.rb
class ChecklistSharesController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def accept
    email = params[:email]
    checklist_id = params[:checklist_id]

    user = User.find_by(email: email)
    flash_and_redirect('The user does not exist') unless user

    checklist_share = ChecklistShare.find_by(user: user, checklist_id: checklist_id)
    flash_and_redirect('We could not find this invitation') unless checklist_share

    checklist_share.update(accepted: true)
    flash[:success] = 'You have accepted the Checklist'
    redirect_to root_path
  end

  def create
    begin
      checklist = Checklist.find(params[:checklist_id])
      checklist.share_with(current_user, params[:email])
      flash[:success] = "Checklist shared with #{params[:email]}!"
    rescue ActiveRecord::RecordInvalid => e
      flash[:error] = e.message
    end
    redirect_to root_path
  end

  private

  def flash_error_message_and_redirect(msg)
    (flash[:error] = msg) && redirect_to(root_path)
  end
end

app/controllers/checklists_controller.rb
class ChecklistsController < ApplicationController
  before_action :authenticate_user!

  def index
    @checklists = Checklist.all
  end

  def show
    @checklist = Checklist.find(params[:id])
  end

  def update
    @checklist = Checklist.find(params[:id])
    @checklist.update(checklist_params)
  end

  private

  def checklist_params
    params.require(:checklist).permit(:title, :template,
      checklist_items: %i[title completed])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def checklist_item_class(item)
    item.completed ? 'completed' : 'uncompleted'
  end

  def checklist_item_button(item)
    item.completed ? 'Mark as Uncompleted' : 'Mark as Completed'
  end
end

app/views/checklist_items/_form.html.slim
= form_for([@checklist, @checklist_item]) do |f|
  = f.text_field :title
  = f.submit "Save"

app/views/checklist_items/edit.html.slim
h3 Edit

= render 'checklist_items/form'

app/views/checklist_items/new.html.slim
h3= "New Item for #{@checklist.title}"

= render 'checklist_items/form'

app/views/checklists/index.html.slim
- content_for(:title, "Checklists")

h2 Checklists
h3 Here are some available checklists to start with

ul.checklist-list.pure-g
  - @checklists.each do |checklist|
    li.checklist-item.pure-u-1
      = link_to checklist.title, checklist_path(checklist)

small This app was deployed using Kubernetes

app/views/checklists/show.html.slim
- content_for(:title, "#{@checklist.title} | Produciton")

div.pure-g
  = form_tag(checklist_shares_path, class: "pure-form")
    = text_field_tag :email,nil, {placeholder: "Share this Checklist", id: "share-checklist-email"}
    = hidden_field_tag :checklist_id, @checklist.id
    = submit_tag "Share", id: "share-checklist-#{@checklist.id}", class: "pure-button"
    div.pure-u-1
      h3
        = @checklist.title
      = link_to "Add Item", new_checklist_checklist_item_path(@checklist)
ul.checklist-list.pure-menu-list
  - @checklist.checklist_items.each do |item|
    li.checklist-item{ class=checklist_item_class(item) id="item-#{item.id}" }
      div.pure-u-1-2
        = link_to item.title, '#'
      div.pure-u-1-2
        = form_for([@checklist, item]) do |f|
          = f.hidden_field :completed, {value: !item.completed}
          = f.submit checklist_item_button(item), id: "complete-checklist-item-#{item.id}", class: "pure-button"
        div
          = link_to 'Edit', edit_checklist_checklist_item_path(@checklist, item)
        div
          = link_to 'Delete', checklist_checklist_item_path(@checklist, item),
            method: :delete, id: "delete-#{item.id}", data: {confirm: 'Are you sure?'}
  - if @checklist.all_done?
    h3 Everything's finished!

app/views/layouts/application.html.slim
doctype html
html
  head
    title
     = content_for?(:title) ? yield(:title) : "Produciton"
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    link crossorigin="anonymous" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w" rel="stylesheet"
  body
    - flash.each do |key, value|
      div{class= "alert alert-#{key}"}= value
    div.pure-g.pure-u-1
      = yield